#! /usr/bin/env python

import rospy
from sensor_msgs.msg import Imu

def callback(data):
    print(data)
    
Imu_sub=rospy.Subscriber("/steer_bot/imu_data", Imu, callback)
r=rospy.Rate(10)
r.sleep()